name: Sync CDN with master branch

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches:
      - 'master'
    paths:
      - 'res/**'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge master into cdn
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git switch cdn
          git merge -Xtheirs --rebase origin/master
          git push origin cdn

