name: Sync CDN with master branch

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches:
      - 'master'
    paths:
      - 'res/**'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge master into CDN
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git switch cdn
          git rebase -Xtheirs origin/master
          git push -f origin cdn

  # Actions run with default credentials will not auto-trigger other actions,
  # so we run deploy-cdn manually here.
  deploy-cdn:
    uses: unnecessarydave/cdntest/.github/workflows/deploy-cdn.yml@master
    needs: sync
