name: Update NT/U21 coachesin CDN

on:
  workflow_dispatch:
  
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    environment:
      name: CHPP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: cdn
      - name: Install Python dependencies
        run: |
          pip install rauth
      - name: Pull data via CHPP
        env:
          CHPP_CONSUMER_KEY: ${{ secrets.CHPP_CONSUMER_KEY }}
          CHPP_CONSUMER_SECRET: ${{ secrets.CHPP_CONSUMER_SECRET }}
          CHPP_ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          CHPP_ACCESS_TOKEN_SECRET: ${{ secrets.CHPP_ACCESS_TOKEN_SECRET }}
        run: |
          python maintainer/locale/UpdateCoaches.py
      - name: Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git commit -am 'automated coaches update'
          git push
