name: Update NT/U21 coaches in CDN

on:
  workflow_dispatch:
  
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-coaches:
    environment:
      name: CHPP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: cdn
      - name: Install Python dependencies
        run: |
          pip install rauth
      - name: Pull data via CHPP
        env:
          CHPP_CONSUMER_KEY: ${{ secrets.CHPP_CONSUMER_KEY }}
          CHPP_CONSUMER_SECRET: ${{ secrets.CHPP_CONSUMER_SECRET }}
          CHPP_ACCESS_TOKEN_KEY: ${{ secrets.CHPP_ACCESS_TOKEN_KEY }}
          CHPP_ACCESS_TOKEN_SECRET: ${{ secrets.CHPP_ACCESS_TOKEN_SECRET }}
        run: |
          [[ -z "${CHPP_CONSUMER_KEY}" ]] && echo "CHPP_CONSUMER_KEY not set" && exit 1
          [[ -z "${CHPP_CONSUMER_SECRET}" ]] && echo "CHPP_CONSUMER_SECRET not set" && exit 1
          [[ -z "${CHPP_ACCESS_TOKEN_KEY}" ]] && echo "CHPP_ACCESS_TOKEN_KEY not set" && exit 1
          [[ -z "${CHPP_ACCESS_TOKEN_SECRET}" ]] && echo "CHPP_ACCESS_TOKEN_SECRET not set" && exit 1
          python maintainer/locale/updateCoaches.py
      - name: Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git commit -am 'automated coaches update'
          git push
