name: Update CDN
description: Update CDN with latest data

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-cdn
  cancel-in-progress: true

jobs:
  staff:
    if: github.repository == 'unnecessarydave/cdntest' && always()
    uses: unnecessarydave/cdntest/.github/workflows/update-staff.yml@master
    secrets: inherit
  coaches:
    if: github.repository == 'unnecessarydave/cdntest' && always()
    uses: unnecessarydave/cdntest/.github/workflows/update-coaches.yml@master
    needs: staff
    secrets: inherit
